# Autor {.unnumbered}

Santiago Botero es ingeniero administrador de la 
[Universidad Nacional de Colombia][unal] y maestro en economía del 
[Centro de Investigación y Docencia Económicas][cide] (CIDE). Tiene particular
interés en el análisis de datos como herramienta para el análisis de la política
antimonopolio y actualmente se encuentra estudiando una especialización en
ciencia de datos impartida en línea ([información aquí][coursera]).

Nació y creció en Medellín, una ciudad de clima agradable sobre las montañas de
los Andes. Llegó a México a mediados del 2012 para realizar sus estudios de
maestría; se ha enamorado del país y allí ha desarrollado su carrera en asuntos
de competencia económica.

Actualmente trabaja en la Autoridad Investigadora de la 
[Comisión Federal de Competencia Económica (Cofece)][cofece], en donde ha
liderado diversas investigaciones sobre condiciones de mercado. Previamente,
trabajó en otras áreas de la Cofece y en el 
[Instituto Federal de Telecomunicaciones][ift], también dedicado a la política
antimonopolios mexicana.

Es profesor de cátedra en el [Tec de Monterrey][tec] desde el primer semestre
de 2018, en donde ha impartido clases de macroeconomía intermedia y 
economía de la empresa. Previamente, fue laboratorista de diversos cursos en
el CIDE.

[unal]: http://unal.edu.co/
[cide]: https://www.cide.edu/
[coursera]: https://www.coursera.org/specializations/jhu-data-science
[cofece]: https://www.cofece.mx/
[ferri]: https://www.cofece.mx/falta-de-competencia-efectiva-en-el-transporte-ferroviario-de-productos-quimicos/
[ift]: http://www.ift.org.mx/
[tec]: https://tec.mx/es